name: Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install
          npm ci

      - name: Run Cypress tests
        id: cypress
        run: npm run test:ci

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-reports
          path: cypress/reports

      - name: Prepare test results
        id: prepare-results
        if: always()
        run: |
          # Create a temporary file with the complete payload
          echo '{
            "repository": "${{ github.repository }}",
            "workflow": "${{ github.workflow }}",
            "run_id": "${{ github.run_id }}",
            "status": "${{ job.status }}",
            "test_results": '$(cat cypress/reports/mochawesome.json)'}' > webhook_payload.json

      - name: Send webhook
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d @webhook_payload.json \
            ${{ secrets.WEBHOOK_URL }}
