name: Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        id: cypress
        run: npm run test:ci

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-reports
          path: cypress/reports

      - name: Read test results
        id: test-results
        if: always()
        run: |
          TEST_RESULTS=$(cat cypress/reports/json/mochawesome.json)
          echo "results<<EOF" >> $GITHUB_ENV
          echo "$TEST_RESULTS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Send webhook notification
        if: always()
        uses: distributhor/workflow-webhook@v3
        env:
          webhook_url: "https://webhook-test.com/e091dc6135eb410d139d87ba693bb01a"
          data: '{"repository": "${{ github.repository }}", "workflow": "${{ github.workflow }}", "run_id": "${{ github.run_id }}", "status": "${{ job.status }}", "test_results": ${{ env.results }}}'
