name: Webhook Notification

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Cypress Tests"]
    types: [completed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        if: always()
        uses: dawidd6/action-download-artifact@v3
        continue-on-error: true
        with:
          workflow: cypress.yml
          name: cypress-reports
          path: cypress/reports
          workflow_conclusion: completed
          run_id: ${{ github.event.workflow_run.id }}
          
      - name: Send notification
        if: always()
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          echo "Listing contents of cypress/reports directory:"
          ls -R cypress/reports || echo "Reports directory not found"
          
          if [ -f "cypress/reports/mochawesome.json" ]; then
            echo "Found mochawesome.json file"
            TEST_RESULTS=$(cat cypress/reports/json/mochawesome.json)
            curl -X POST \
              -H "Content-Type: application/json" \
              -d "{
                \"status\": \"${{ github.event.workflow_run.conclusion }}\",
                \"repo\": \"${{ github.repository }}\",
                \"testResults\": ${TEST_RESULTS}
              }" \
              $WEBHOOK_URL
          else
            curl -X POST \
              -H "Content-Type: application/json" \
              -d "{
                \"status\": \"${{ github.event.workflow_run.conclusion }}\",
                \"repo\": \"${{ github.repository }}\",
                \"error\": \"No test results found\"
              }" \
              $WEBHOOK_URL
          fi
