name: Webhook Notification

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Cypress Tests"]
    types: [completed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        if: always()
        uses: dawidd6/action-download-artifact@v3
        continue-on-error: true
        with:
          workflow: cypress.yml
          name: cypress-reports
          path: cypress/reports
          workflow_conclusion: completed
          run_id: ${{ github.event.workflow_run.id }}
          
      - name: Send notification
        if: always()
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          echo "Listing contents of cypress/reports directory:"
          ls -R cypress/reports || echo "Reports directory not found"
          
          if [ -f "cypress/reports/mochawesome.json" ]; then
            echo "Found mochawesome.json file"
          
            # Validate JSON and create formatted payload
            echo "Creating payload..."
            jq -c \
              --arg status "${{ job.status }}" \
              --arg repo "${{ github.repository }}" \
              '{status: $status, repo: $repo, testResults: .}' \
              cypress/reports/mochawesome.json > payload.json
          
            echo "Payload size: $(wc -c < payload.json) bytes"
            echo "First 1000 characters of payload:"
            head -c 1000 payload.json
          
            echo "Sending payload..."
            curl -v -X POST \
              -H "Content-Type: application/json" \
              --data @payload.json \
              $WEBHOOK_URL
          
            echo "Cleaning up..."
            rm payload.json
          else
            echo "No mochawesome.json found, sending error notification"
            curl -X POST \
              -H "Content-Type: application/json" \
              -d "{\"status\": \"${{ job.status }}\", \"repo\": \"${{ github.repository }}\", \"error\": \"No test results found\"}" \
              $WEBHOOK_URL
          fi
